import { useRef, useState } from "react";
import {
  Export as ExportIcon,
  Download,
  Copy,
  Upload,
  Code,
  FileArrowDown,
  Warning,
} from "phosphor-react";
import { Card } from "../components/ui/Card";
import { Button } from "../components/ui/Button";
import { useConnectionStore } from "../lib/store";
import { toast } from "sonner";
import type { Connection } from "../lib/types";

export function Export() {
  const { connections, add, setAll } = useConnectionStore();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [importError, setImportError] = useState<string>("");

  // Strip credentials for export
  const exportConnections = connections.map(conn => ({
    ...conn,
    username: "",  // Strip username for security
    // Password is never stored anyway, so no need to strip it
  }));

  const jsonPreview = JSON.stringify(exportConnections, null, 2);

  // Export as JSON download (without credentials)
  const handleExportJSON = () => {
    const dataStr = JSON.stringify(exportConnections, null, 2);
    const blob = new Blob([dataStr], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `rclone-mounter-connections-${new Date().toISOString().split("T")[0]}.json`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success("Connections exported (credentials excluded for security)");
  };

  // Copy to clipboard
  const handleCopyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(jsonPreview);
      toast.success("Copied to clipboard");
    } catch (err) {
      toast.error("Failed to copy to clipboard");
    }
  };

  // Import from JSON
  const handleImportJSON = () => {
    fileInputRef.current?.click();
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    try {
      const text = await file.text();
      const data = JSON.parse(text);

      // Validate structure
      if (!Array.isArray(data)) {
        throw new Error("Invalid format: Expected an array of connections");
      }

      // Validate each connection has required fields
      const requiredFields = ["id", "name", "local_ip", "port", "drive_letter"];
      for (const conn of data) {
        for (const field of requiredFields) {
          if (!(field in conn)) {
            throw new Error(`Missing required field: ${field}`);
          }
        }
      }

      // Import connections and prompt for credentials
      const importedConnections: Connection[] = [];

      for (const conn of data) {
        // Prompt for credentials for each connection
        const username = prompt(`Enter username for "${conn.name}":`);
        if (!username) {
          toast.warning(`Skipped: ${conn.name} (no username provided)`);
          continue;
        }

        const password = prompt(`Enter password for "${conn.name}":`);
        if (!password) {
          toast.warning(`Skipped: ${conn.name} (no password provided)`);
          continue;
        }

        // Create rclone remote
        try {
          const url = `http://${conn.local_ip}:${conn.port}`;
          await invoke("create_remote", {
            name: conn.name,
            url,
            vendor: "other",
            user: username,
            pass: password,
          });

          // Add connection with credentials
          importedConnections.push({
            ...conn,
            username,
          } as Connection);
        } catch (err) {
          toast.error(`Failed to create remote for ${conn.name}: ${err}`);
        }
      }

      if (importedConnections.length > 0) {
        setAll([...connections, ...importedConnections]);
        setImportError("");
        toast.success(`Imported ${importedConnections.length} connection(s)`);
      } else {
        toast.warning("No connections were imported");
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : "Invalid JSON file";
      setImportError(message);
      toast.error(message);
    }

    // Reset input
    e.target.value = "";
  };

  // Generate PowerShell script for a connection
  const generatePowerShellScript = (conn: Connection): string => {
    const url = conn.network_mode === "tailscale"
      ? `http://${conn.tailscale_ip}:${conn.port}`
      : `http://${conn.local_ip}:${conn.port}`;

    return `# Rclone Mount Script - ${conn.name}
# Generated by Rclone Mounter GUI

$driveLetter = "${conn.drive_letter}"
$webdavUrl = "${url}"
$username = "${conn.username}"

# Check if drive is already mounted
if (Test-Path "$driveLetter:\\") {
    Write-Host "Drive $driveLetter is already in use" -ForegroundColor Yellow
    exit 1
}

# Mount the WebDAV drive
Write-Host "Mounting ${conn.name} to $driveLetter..." -ForegroundColor Cyan

rclone mount "${conn.name}:" "$driveLetter:" \`
  --vfs-cache-mode full \`
  --webdav-url "$webdavUrl" \`
  --webdav-user "$username" \`
  --no-console

# This script will keep running until you press Ctrl+C
`;
  };

  const handleDownloadScript = (conn: Connection) => {
    const script = generatePowerShellScript(conn);
    const blob = new Blob([script], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `mount-${conn.name.toLowerCase().replace(/\s+/g, "-")}.ps1`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success(`PowerShell script downloaded: ${conn.name}`);
  };

  return (
    <div className="h-full overflow-y-auto content-scroll">
      <div className="px-10 py-8 pb-12 max-w-3xl w-full mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-2xl font-semibold text-text-primary tracking-tight mb-2 flex items-center gap-3">
            <ExportIcon size={28} weight="duotone" className="text-accent-blue" />
            Export & Import
          </h1>
          <p className="text-[13px] text-text-secondary">
            Backup your connections or generate standalone scripts
          </p>
        </div>

        <div className="space-y-6">
          {/* Section A - Export */}
          <Card className="p-6">
            <h2 className="text-base font-semibold text-text-primary mb-4 flex items-center gap-2">
              <Download size={18} weight="duotone" className="text-accent-green" />
              Export Connections
            </h2>
            <div className="space-y-4">
              <div className="flex items-center gap-3">
                <Button
                  variant="primary"
                  size="md"
                  onClick={handleExportJSON}
                  disabled={connections.length === 0}
                  className="gap-2"
                >
                  <FileArrowDown size={16} weight="bold" />
                  Export as JSON
                </Button>
                <Button
                  variant="ghost"
                  size="md"
                  onClick={handleCopyToClipboard}
                  disabled={connections.length === 0}
                  className="gap-2"
                >
                  <Copy size={16} weight="bold" />
                  Copy to Clipboard
                </Button>
              </div>

              {/* Preview */}
              <div>
                <label className="block text-[13px] font-medium text-text-secondary mb-2">
                  Preview (credentials excluded for security)
                </label>
                <textarea
                  readOnly
                  value={
                    connections.length === 0
                      ? "No connections to export"
                      : jsonPreview
                  }
                  className="w-full h-48 px-3 py-2 rounded-lg bg-white/[0.03] border border-white/[0.06] text-[12px] text-text-primary font-mono resize-none focus:outline-none"
                />
              </div>
            </div>
          </Card>

          {/* Section B - Import */}
          <Card className="p-6">
            <h2 className="text-base font-semibold text-text-primary mb-4 flex items-center gap-2">
              <Upload size={18} weight="duotone" className="text-accent-purple" />
              Import Connections
            </h2>
            <div className="space-y-3">
              <p className="text-[13px] text-text-secondary">
                Import connections from a JSON file. You'll be prompted to enter credentials for each connection, which will be securely stored in rclone's config.
              </p>
              <Button
                variant="default"
                size="md"
                onClick={handleImportJSON}
                className="gap-2"
              >
                <Upload size={16} weight="bold" />
                Import JSON File
              </Button>
              <input
                ref={fileInputRef}
                type="file"
                accept=".json"
                onChange={handleFileChange}
                className="hidden"
              />
              {importError && (
                <div className="p-3 rounded-lg bg-accent-red/10 border border-accent-red/30 flex items-start gap-2">
                  <Warning size={16} className="text-accent-red mt-0.5" weight="bold" />
                  <p className="text-[13px] text-accent-red">{importError}</p>
                </div>
              )}
            </div>
          </Card>

          {/* Section C - Generate PowerShell Scripts */}
          <Card className="p-6">
            <h2 className="text-base font-semibold text-text-primary mb-4 flex items-center gap-2">
              <Code size={18} weight="duotone" className="text-accent-amber" />
              PowerShell Scripts
            </h2>
            <p className="text-[13px] text-text-secondary mb-4">
              Generate standalone mount scripts for each connection
            </p>
            {connections.length === 0 ? (
              <div className="py-8 text-center">
                <p className="text-[13px] text-text-tertiary">
                  No connections available. Add a connection first.
                </p>
              </div>
            ) : (
              <div className="space-y-3">
                {connections.map((conn) => (
                  <div
                    key={conn.id}
                    className="flex items-center justify-between p-3 rounded-lg bg-white/[0.03] border border-white/[0.06]"
                  >
                    <div>
                      <div className="text-[13px] font-medium text-text-primary">
                        {conn.name}
                      </div>
                      <div className="text-[11px] text-text-tertiary">
                        Drive {conn.drive_letter}: • {conn.network_mode} mode
                      </div>
                    </div>
                    <Button
                      variant="default"
                      size="sm"
                      onClick={() => handleDownloadScript(conn)}
                      className="gap-1.5"
                    >
                      <Download size={14} weight="bold" />
                      Download Script
                    </Button>
                  </div>
                ))}
              </div>
            )}
          </Card>
        </div>
      </div>
    </div>
  );
}
